<a href="https://colab.research.google.com/github/anshuman4515/Capstone-project/blob/main/merge_flats_houses.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import pandas as pd
import numpy as np

In [9]:
flats=pd.read_csv('/content/flats_cleaned.csv')
houses=pd.read_csv('/content/house_cleaned.csv')

In [10]:
flats.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,flat,maa bhagwati residency,0.45,5000.0,900.0,Carpet area: 900 (83.61 sq.m.),2.0,2.0,1.0,not available,"Krishna Colony, Gurgaon, Haryana",4.0,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,flat,Apna Enclave,0.50,7692.0,650.0,Carpet area: 650 (60.39 sq.m.),2.0,2.0,1.0,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1.0,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,flat,Tulsiani Easy in Homes,0.40,6722.0,595.0,Carpet area: 595 (55.28 sq.m.),2.0,2.0,3.0,not available,"Sohna, Gurgaon, Haryana",12.0,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,flat,Smart World Orchard,1.47,12250.0,1200.0,Carpet area: 1200 (111.48 sq.m.),2.0,2.0,2.0,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2.0,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,flat,Parkwood Westend,0.70,5204.0,1345.0,Super Built up area 1345(124.95 sq.m.),2.0,2.0,3.0,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5.0,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [11]:
houses.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,house,bptp visionnaire,5.25,20115.0,2610.0,Plot area 290(242.48 sq.m.),5,4,NaN,servant room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3.0,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,house,independent,5.70,105751.0,539.0,Plot area 539(50.07 sq.m.),5,4,2.0,"store room,pooja room,servant room","Sector 21A Faridabad, Gurgaon, Haryana",2.0,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,house,independent,2.10,38251.0,549.0,Plot area 61(51 sq.m.),10,10,NaN,servant room,"Sushant Lok Phase 1, Gurgaon, Haryana",5.0,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,house,independent,5.00,43066.0,1161.0,Plot area 129(107.86 sq.m.),21,21,NaN,servant room,"Sector 54 Gurgaon, Gurgaon, Haryana",5.0,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,house,independent,3.00,53763.0,558.0,Plot area 62(51.84 sq.m.),12,12,NaN,others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5.0,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [12]:
df=pd.concat([flats,houses], ignore_index=True)

In [13]:
df=df.sample(df.shape[0], ignore_index=True)

In [14]:
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,3 Bedroom House for sale in Sohna,house,signature global park,0.85,7589.0,1120.0,Built Up area: 1120 (104.05 sq.m.),3.0,2.0,2.0,not available,"Signature Global Park 4 Phase Ii, Sector 36 So...",1.0,NaN,Jun 2024,"['Sector 55-56 metro', 'Global city centre', '...",Property is park facing with plc. Corner and p...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...","['Park', 'Visitor Parking']","['Environment4 out of 5', 'Lifestyle4 out of 5..."
1,3 BHK Flat in Sector 102 Gurgaon,flat,Conscient Heritage Max4.3 ★,1.75,9062.0,1931.0,Super Built up area 1931(179.4 sq.m.),3.0,4.0,NaN,servant room,"Abcd, Sector 102 Gurgaon, Gurgaon, Haryana",16.0,South,1 to 5 Year Old,"['Huda Metro Station', 'Ocus Medley Mall', 'Th...",National standard football field with flood li...,"['1 Stove', '5 AC', '1 Modular Kitchen', '1 Ch...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area5 out of 5', 'Construction5 out of..."
2,2 BHK Flat in Sector 108 Gurgaon,flat,Raheja Vedaanta3.6 ★,0.70,4666.0,1500.0,Built Up area: 1468 (136.38 sq.m.)Carpet area:...,2.0,2.0,1.0,not available,"Sector 108, Sector 108 Gurgaon, Gurgaon, Haryana",10.0,West,5 to 10 Year Old,NaN,"2 bath, semi furnished, 10th floor (Of 16), ov...",NaN,NaN,"['Green Area4 out of 5', 'Amenities4 out of 5'..."
3,4 BHK Flat in Sector 84 Gurgaon,flat,Alpha Corp GurgaonOne 844.0 ★,2.24,6523.0,3434.0,Super Built up area 3434(319.03 sq.m.)Carpet a...,4.0,4.0,3.0,servant room,"Sector 84 Gurgaon, Gurgaon, Haryana",12.0,West,1 to 5 Year Old,"['Delhi Public School', 'Raheja Market', 'Sapp...",Check out this 4 bhk apartment for sale in alp...,NaN,"['Intercom Facility', 'Lift(s)', 'Maintenance ...","['Green Area5 out of 5', 'Construction5 out of..."
4,4 BHK Flat in Sector 110 Gurgaon,flat,Indiabulls Enigma,3.40,10000.0,3400.0,Super Built up area 3400(315.87 sq.m.)Built Up...,4.0,5.0,3.0,servant room,"Sector 110 Gurgaon, Gurgaon, Haryana",10.0,South-West,1 to 5 Year Old,"['Dwarka Sector 21 Metro Station', 'Gurgaon Dr...",Spacious 4 bhk flat in indiabulls enigma at se...,"['6 AC', 'No Bed', 'No Chimney', 'No Curtains'...","['Water purifier', 'Security / Fire Alarm', 'P...","['Environment4 out of 5', 'Lifestyle4 out of 5..."

In [15]:
df.to_csv('gurgaon_properties', index=False)